{% set version = "1.3.0" %}

package:
  name: poetry
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry/poetry-{{ version }}.tar.gz
  sha256: d42943b44e80f5afafebdb696393cbdbcc750aecfaa6801174a4da42147c73fc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - poetry = poetry.console.application:main

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.1.0
  run:
    # Update version number in URL before checking dependencies
    # https://github.com/python-poetry/poetry/blob/1.3.0/pyproject.toml
    - python
    - poetry-core 1.4.0
    - poetry-plugin-export >=1.2.0,<2.0.0
    - backports.cached-property >=1.0.2,<2.0.0  # [py<38]
    - cachecontrol >=0.12.9,<0.13.0

    # cachecontrol filecache extra
    - filelock >=3.8.0

    - cleo >=2.0.0,<3.0.0
    - crashtest >=0.4.1,<0.5.0
    - dulwich >=0.20.46,<0.21.0
    - filelock >=3.8.0,<4.0.0
    - html5lib >=1.0,<2.0
    - importlib-metadata >=4.4,<5.0  # [py<310]
    - jsonschema >=4.10.0,<5.0.0
    - keyring >=23.9.0,<24.0.0
    - packaging >=20.4
    - pexpect >=4.7.0,<5.0.0
    - pkginfo >=1.5,<2.0
    - platformdirs >=2.5.2,<3.0.0
    - requests >=2.18,<3.0
    - requests-toolbelt >=0.9.1,<0.11.0
    - shellingham >=1.5,<2.0
    - tomli >=2.0.1,<3.0.0  # [py<311]
    - tomlkit >=0.11.1,<1.0.0,!=0.11.2,!=0.11.3
    - trove-classifiers >=2022.5.19
    # See <https://github.com/python-poetry/poetry/pull/6950>
    - virtualenv >=20.4.3,<21.0.0,!=20.4.5,!=20.4.6  # [not win or py!=39]
    - virtualenv >=20.4.3,<20.16.6,!=20.4.5,!=20.4.6  # [win and py==39]
    - xattr >=0.10.0,<0.11.0  # [darwin]
    - urllib3 >=1.26.0,<2.0.0

    # `poetry` entry point fails without this:
    - lockfile >=0.9

test:
  requires:
    - pip
  commands:
    - pip check
    - poetry -V
  imports:
    - poetry
    - poetry.config

about:
  home: https://python-poetry.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python dependency management and packaging made easy
  dev_url: https://github.com/python-poetry/poetry
  doc_url: https://python-poetry.org/docs/

extra:
  recipe-maintainers:
    - ocefpaf
    - maresb
    - xylar
